spring:
#  datasource:
#    url: jdbc:mariadb://localhost:3306/alfirst?useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: admin
#    driver-class-name: org.mariadb.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MariaDBDialect
#        show_sql: true
#        format_sql: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop  # 테스트용이므로 테스트마다 테이블 생성 및 제거
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis:
      host:
      port:
      username:
      password:
